spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/lsg_sys?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: ENC(crRQ4MChROAdWrnaGMI/h3vq5jjdOZC3iCIqVgBz3b73YTD1qJL3ogT68yGGsPy9)
      validation-query: select 1 from dual
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.100.137
    port: 6379
    password: ENC(crRQ4MChROAdWrnaGMI/h3vq5jjdOZC3iCIqVgBz3b73YTD1qJL3ogT68yGGsPy9)
    lettuce:
      pool:
        min-idle: 0
        max-active: 3
        max-idle: 10
        max-wait: 30000
mybatis:
  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.duanxin.lsg.persistent.module

## 微信登陆
wx:
  miniapp:
#    appid: ENC(U8Z6P3piQM0YcFDr8V6/zD5C2kiA+ZnsnLRbAa22ENEo6OFacIc5JCFY5iWyz1eN3GP/otIv3hhAowKQVQApzQ==)
    appid: wx1277146e46782655
#    secret: ENC(Qd4eCUdP32WQ9QPzyGf8IvuQnM2RNekxC0Izo5DGkcldTbR0LreS+bsSTfjJdnXOePa5hijpBE653IVdNvkuUNGnOI0vOCmW1aQalwh1fDs=)
    secret: e8b21eeeb69a4e1d2d4f461c27c46009
    token:
    aes-key:
    msg-data-format:


## 加密解密
jasypt:
  encryptor:
    password: 135792468

## 线程池参数
event:
  task:
    corePoolSize: 8
    maximumPoolSize: 16
    keepAliveTime: 3000
    workQueueSize: 500
    threadPoolName: event-task